# Generated by Django 4.0 on 2022-01-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Fname',
            new_name='FName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Lname',
            new_name='LName',
        ),
    ]
