# Generated by Django 4.0 on 2022-01-19 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_patient_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=20)),
                ('LName', models.CharField(max_length=20)),
                ('Address', models.TextField(blank=True)),
                ('PNumber', models.IntegerField(default=0)),
                ('Disease', models.TextField(blank=True)),
                ('Bloodgroup', models.CharField(max_length=2)),
                ('Unit', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
